### PR TITLE
Fixed some problems with Entity and Context in comments

### PR DESCRIPTION
**Pull request by spericas**
See #1179.

### CODE REVIEW

**Comment by spericas** [comment]
@NicoNes

**Review by jamezp — APPROVED** [review]

**Comment by NicoNes** [comment]
@spericas What about these ones ?

- https://github.com/jakartaee/rest/blob/release-4.0/jaxrs-api/src/main/java/jakarta/ws/rs/core/Application.java#L30
- https://github.com/jakartaee/rest/blob/release-4.0/jaxrs-api/src/main/java/jakarta/ws/rs/core/Configuration.java#L36

**Comment by spericas** [comment]
> @spericas What about these ones ?
> 
> * https://github.com/jakartaee/rest/blob/release-4.0/jaxrs-api/src/main/java/jakarta/ws/rs/core/Application.java#L30
> * https://github.com/jakartaee/rest/blob/release-4.0/jaxrs-api/src/main/java/jakarta/ws/rs/core/Configuration.java#L36

@NicoNes Fixed those and a couple more, thx.

**Review by jamezp — APPROVED** [review]
LGTM

**Comment by spericas** [comment]
Needs more approvals please @jansupol @mkarg @jim-krueger

**Review by jim-krueger — COMMENTED** [review]
Please update Copyright dates on all files.   Otherwise LGTM.

**Review by arjantijms — APPROVED** [review]

**Comment by spericas** [comment]
> Please update Copyright dates on all files. Otherwise LGTM.

Done, thanks.

**Review by jim-krueger — APPROVED** [review]

**Pull request merged**
