### PR TITLE
MediaType - Missing JSON Merge Patch type #1141

### PR DESCRIPTION
**Pull request by ribandcoder**
Fix this:
https://github.com/jakartaee/rest/issues/1141

### CODE REVIEW

**Review by chkal — APPROVED** [review]
LGTM. Thanks!

**Review by spericas — APPROVED** [review]

**Review by jamezp — APPROVED** [review]

**Review by jansupol — APPROVED** [review]

**Comment by jim-krueger** [comment]
Please add `APPLICATION_MERGE_PATCH_JSON_TYPE` to `jaxrs-tck/src/main/resources/ee/jakarta/tck/ws/rs/signaturetest/jakarta.ws.rs.sig_4.0.0`

**Comment by jamezp** [comment]
Just an FYI this can be done with the following command:
```
mvn clean package -Precord-signature,EFTL
```
This generates a file named `jakarta.ws.rs.sig_4.0.0-SNAPSHOT` in the `jaxrs-tck/target` directory. From there you need to copy the content over to the `jaxrs-tck/src/main/resources/ee/jakarta/tck/ws/rs/signaturetest/jakarta.ws.rs.sig_4.0.0` file. 

Note this if #1244 is not merged first, this will also include the removal of the Jakarta XML Binding.

**Comment by spericas** [comment]
Replaced by PR #1246.

**Pull request closed without merging**
