### PR TITLE
[742] TCK Tests for ContextResolver<Jsonb>

### PR DESCRIPTION
**Pull request by mkarg**
This PR is amending the our new TCK by tests for `ContextResolver<Jsonb>`.

See https://github.com/eclipse-ee4j/jaxrs-api/pull/973 for the according spec change.

### CODE REVIEW

**Comment by andymc12** [comment]
@mkarg thanks for putting this together.  It seems like this uses the Java SE APIs in place of something like Arquillian. I would rather see the TCK use Arquillian and then use a plugin for the Java SE APIs.  That way a container-based implementation like Liberty, GlassFish or Wildfly, etc. doesn't need to build an adapter to fit into the Java SE APIs. This is something that I've been thinking about (particularly for the multipart TCK tests) but haven't started yet - if you want, I can help with integrating with Arquillian.

**Comment by mkarg** [comment]
I understand your concerns and would be happy if you put a commit ontop which reworks *this* test case by replacing SeBootstrap with Arquilian. Can you please send a MR against my fork?

OTOH, I would also by happy if Payara opens their existing SE bootstrap to GlassFash, and if Wildly would take the chance to support SE. :-)

**Comment by mkarg** [comment]
Just noticed, there is an alpha release of JUnit 5 support for Arquillian:

https://search.maven.org/search?q=g:org.jboss.arquillian.junit5

Maybe this works for our cases?

Maybe we should have *another* PR that just puts Arquillian ontop the new new JDK, and we suspend *this* PR meanwhile?

**Comment by andymc12** [comment]
I had to leave before the discussion was finished, but TCK technologies was the main topic at today's Jakarta EE Platform call. I don't think they reached any consensus, but one suggestion was to use TestNG and Arquillian, as MicroProfile TCKs have proven that they can work.  Personally, I'd prefer JUnit 5, but if we run into alpha-level issues, we might want to fallback to TestNG.

**Comment by mkarg** [comment]
I'd also rather stick with JUnit 5 due its vast community, and in the end, it is our own decision, not the platform's. We are not bound to platform decisions on the level of implementations. But certainly, TestNG is a valid, temporary fallback as long as JUnit 5 is *really failing* with Arquilian. When do you have time to look into this? I'm excited to see it run!

**Comment by mkarg** [comment]
@andymc12 Will you provide the needed rework to make this test use Arquillian?

**Comment by andymc12** [comment]
@mkarg Yes, I'm hoping to start looking at it tomorrow.  I'm not sure yet whether it will make more sense to append to your PR or to start a new one, but once I've dug into this a little deeper, I'll let you know. Thanks.

**Comment by mkarg** [comment]
I have not used Arquillian before, but I would be happy to rewrite this test if someone helps me with the Arquillian part. :-)

**Comment by mkarg** [comment]
> @mkarg Yes, I'm hoping to start looking at it tomorrow. I'm not sure yet whether it will make more sense to append to your PR or to start a new one, but once I've dug into this a little deeper, I'll let you know. Thanks.

I think it makes sense to simply put a commit ontop of this PR *or* to rebase your PR on this one.

**Comment by mkarg** [comment]
@andymc12 You wanted to put a commit ontop for migration to Arquilian. Is that still your plan?

**Comment by andymc12** [comment]
> @andymc12 You wanted to put a commit ontop for migration to Arquilian. Is that still your plan?

I was planning to wait for one of the arquillian PRs to get merged first, then apply this test.

**Comment by mkarg** [comment]
> > @andymc12 You wanted to put a commit ontop for migration to Arquilian. Is that still your plan?
> 
> I was planning to wait for one of the arquillian PRs to get merged first, then apply this test.

Seems to be done, so... "ping". ;-)

**Comment by jelemux** [comment]
@mkarg I looked into this as you said I could in our last email correspondence and it seems doable for me.  
It would be good if I could rely on existing utilities like TestUtil and JAXRSCommonClient though, so could you please fetch upstream real quick? Then I can prepare a PR on your fork, which in turn could be merged here.

**Comment by mkarg** [comment]
> @mkarg Could you please fetch upstream real quick? Then I can prepare a PR on your fork, which in turn could be merged here.

@jelemux Thank you for chiming in. I just rebased on master and force-pushed. Yes, simply open a PR against my fork so I can merge your adjustments.

**Comment by mkarg** [comment]
@jelemux Do you see progress?

**Comment by jelemux** [comment]
Hey sorry. Didn't find time over the christmas holidays. Today I found some time again but unfortunately was not able to test them yet.

**Comment by jelemux** [comment]
@mkarg I made some good progress today. 
Unfortunately I was not able to get it to work yet. When I try to make a request to the endpoint, I always get back a 404. 
You can see my changes here if you want to take a look: https://github.com/jelemux/jaxrs-api/tree/tck-742
I wrote something to export the war into the target folder, so it's possible to troubleshoot outside of the test.

**Comment by jelemux** [comment]
@mkarg Got it working. PR https://github.com/mkarg/jaxrs-api/pull/8 is waiting for you.

**Comment by mkarg** [comment]
@spericas @jansupol @chkal @andymc12 Kindly requesting vote for this TCK PR! :-)

**Comment by spericas** [comment]
@mkarg I was trying to figure out the package renaming before evaluating this PR. Based on everything I've read so far, it seems that we should go ahead with some form of renaming.

**Comment by jansupol** [comment]
The TCK used to contain a couple of folders to have the tests organized. This TCK test introduces a new `contextprovider` folder. The `ContextResolver<Jsonb>` requirement comes from the spec document, so I'd advocate for making the `contextprovider` folder a part of `spec` folder.

I also see a possible issue with the private final EchoApplication class. The DI is responsible for creating the instance, but I am not sure whether all the DIs used by vendors are able to create an instance of private final class. I remember RestEasy created a proxy of the Application subclass, but CDI does not seem to be capable of creating a proxy of a final class.

**Comment by jansupol** [comment]
`contextprovider` sounds odd...would `jsonbcontextresolver` be a better name?

**Comment by mkarg** [comment]
> The TCK used to contain a couple of folders to have the tests organized. This TCK test introduces a new `contextprovider` folder. The `ContextResolver<Jsonb>` requirement comes from the spec document, so I'd advocate for making the `contextprovider` folder a part of `spec` folder.

The cause of this is that this test was written *before* the original TCK tests moved into the JAX-RS repository. I'm fine with renaming it, so everybody please comment what the actual name shall be like.

> I also see a possible issue with the private final EchoApplication class. The DI is responsible for creating the instance, but I am not sure whether all the DIs used by vendors are able to create an instance of private final class. I remember RestEasy created a proxy of the Application subclass, but CDI does not seem to be capable of creating a proxy of a final class.

Can a CDI expert please comment whether this is actually forbidden in CDI?

**Comment by mkarg** [comment]
>`contextprovider` sounds odd...would `jsonbcontextresolver` be a better name?

According to [spec chapter 4.3](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#contextprovider) the official term actually *is* "Context Provider". This is not a unit test for the Java interface called `ContextResolver<Jsonb>`, this is a TCK test for the spec term "Context Provider". So `contextprovider` is absolutely correct and anything but "odd".

**Comment by mkarg** [comment]
> The TCK used to contain a couple of folders to have the tests organized. This TCK test introduces a new `contextprovider` folder. The `ContextResolver<Jsonb>` requirement comes from the spec document, so I'd advocate for making the `contextprovider` folder a part of `spec` folder.

Done in https://github.com/eclipse-ee4j/jaxrs-api/pull/976/commits/68f8f5f05248e4adf4dcc04be33f0fe9b6e90b58.

**Comment by mkarg** [comment]
@chkal @andymc12 @jelemux @jansupol @spericas Requesting review. Thanks.

**Review by spericas — APPROVED** [review]
LGTM

**Review by spericas — CHANGES_REQUESTED** [review]
Just realized we need package renaming for this one

**Comment by spericas** [comment]
@mkarg Can we do the package renaming now? Another PR just takes more time and we need wrap this up. Thx.

**Comment by mkarg** [comment]
> @mkarg Can we do the package renaming now? Another PR just takes more time and we need wrap this up. Thx.

Thanks, totally missed this one. Fixed now.

**Comment by mkarg** [comment]
@chkal @andymc12 @jelemux @jansupol @spericas Requesting review again due to package renaming. Thanks.

**Review by jelemux — APPROVED** [review]
LGTM 🎉

**Review by jansupol — APPROVED** [review]

**Pull request merged**
