### PR TITLE
fast-track: 1162 sse broadcast test

### LINKED ISSUE #1162: [TCK Challenge] Order testing of JAXRSClientIT.sseBroadcastTest results
The `ee.jakarta.tck.ws.rs.jaxrs21.ee.sse.ssebroadcaster.JAXRSClientIT.sseBroadcastTest`  expects the results of a client to be in a specific order. Unless I'm missing something, I don't see where there is a requirement that events be received in a specific order. I'm not even sure how the receive order could be guaranteed.

In section [9.1](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#sse_introduction) it states:
> SSE is a messaging protocol where the `event` field corresponds to a topic, and where the `id` field can be used to validate event order and guarantee continuity.

I've been seeing this fail more often on our CI. Though we're still waiting for #1146 to be merged so we can see the messages, when I see it fail with a SNAPSHOT TCK, the contents are all there just in a different order. My assumption is the client receives the responses in a different order due to network activity. 

This test has periodically failed for RESTEasy, but seems to be getting worse on CI. I've never been able to reproduce it locally.

Here are some logs from a failing test:
```
07-18-2023 12:07:00:  TRACE: [WIRE] - << Connection: keep-alive
07-18-2023 12:07:00:  TRACE: [WIRE] - << Content-Length: 5
07-18-2023 12:07:00:  TRACE: [WIRE] - << Content-Type: application/octet-stream
07-18-2023 12:07:00:  TRACE: [WIRE] - << Date: Tue, 18 Jul 2023 12:07:00 GMT
07-18-2023 12:07:00:  TRACE: [WIRE] - << CLOSE
07-18-2023 12:07:00:Client 0 Received message WELCOME3
07-18-2023 12:07:00:Client 0 Received message some_ServiceUnavailableEndpoint_message0
07-18-2023 12:07:00:Client 0 Received message some_ServiceUnavailableEndpoint_message1
07-18-2023 12:07:00:Client 0 Received message some_ServiceUnavailableEndpoint_message2
07-18-2023 12:07:00:Client 0 Received message some_ServiceUnavailableEndpoint_message3
07-18-2023 12:07:00:Client 0 Received message some_ServiceUnavailableEndpoint_message4
07-18-2023 12:07:00:Client 0 Received message some_ServiceUnavailableEndpoint_message5
07-18-2023 12:07:00:Client 0 Received message some_ServiceUnavailableEndpoint_message6
07-18-2023 12:07:00:Client 1 Received message WELCOME1
07-18-2023 12:07:00:Client 1 Received message some_ServiceUnavailableEndpoint_message0
07-18-2023 12:07:00:Client 1 Received message some_ServiceUnavailableEndpoint_message1
07-18-2023 12:07:00:Client 1 Received message some_ServiceUnavailableEndpoint_message2
07-18-2023 12:07:00:Client 1 Received message some_ServiceUnavailableEndpoint_message3
07-18-2023 12:07:00:Client 1 Received message some_ServiceUnavailableEndpoint_message4
07-18-2023 12:07:00:Client 1 Received message some_ServiceUnavailableEndpoint_message5
07-18-2023 12:07:00:Client 1 Received message some_ServiceUnavailableEndpoint_message6
07-18-2023 12:07:00:Client 2 Received message WELCOME2
07-18-2023 12:07:00:Client 2 Received message some_ServiceUnavailableEndpoint_message1
07-18-2023 12:07:00:Client 2 Received message some_ServiceUnavailableEndpoint_message0
07-18-2023 12:07:00:Client 2 Received message some_ServiceUnavailableEndpoint_message2
07-18-2023 12:07:00:Client 2 Received message some_ServiceUnavailableEndpoint_message3
07-18-2023 12:07:00:Client 2 Received message some_ServiceUnavailableEndpoint_message4
07-18-2023 12:07:00:Client 2 Received message some_ServiceUnavailableEndpoint_message5
07-18-2023 12:07:00:Client 2 Received message some_ServiceUnavailableEndpoint_message6
07-18-2023 12:07:00:Client 3 Received message WELCOME4
07-18-2023 12:07:00:Client 3 Received message some_ServiceUnavailableEndpoint_message1
07-18-2023 12:07:00:Client 3 Received message some_ServiceUnavailableEndpoint_message0
07-18-2023 12:07:00:Client 3 Received message some_ServiceUnavailableEndpoint_message2
07-18-2023 12:07:00:Client 3 Received message some_ServiceUnavailableEndpoint_message3
07-18-2023 12:07:00:Client 3 Received message some_ServiceUnavailableEndpoint_message4
07-18-2023 12:07:00:Client 3 Received message some_ServiceUnavailableEndpoint_message5
07-18-2023 12:07:00:Client 3 Received message some_ServiceUnavailableEndpoint_message6
07-18-2023 12:07:00:Client 4 Received message WELCOME0
07-18-2023 12:07:00:Client 4 Received message some_ServiceUnavailableEndpoint_message0
07-18-2023 12:07:00:Client 4 Received message some_ServiceUnavailableEndpoint_message1
07-18-2023 12:07:00:Client 4 Received message some_ServiceUnavailableEndpoint_message2
07-18-2023 12:07:00:Client 4 Received message some_ServiceUnavailableEndpoint_message3
07-18-2023 12:07:00:Client 4 Received message some_ServiceUnavailableEndpoint_message4
07-18-2023 12:07:00:Client 4 Received message some_ServiceUnavailableEndpoint_message5
07-18-2023 12:07:00:Client 4 Received message some_ServiceUnavailableEndpoint_message6
```

As you can see the data is all there, just in a different order than the test expects.

### PR DESCRIPTION
**Pull request by jim-krueger**
Fixes #1162

### CODE REVIEW

**Review by spericas — COMMENTED** [review]
I'm not sure why we target release-3.1.x. I think this should just go to master. @alwin-joseph?

**Comment by alwin-joseph** [comment]
> I'm not sure why we target release-3.1.x. I think this should just go to master. @alwin-joseph?

Yes, if the challenge is accepted the TCK 3.1.4(release-3.1.x branch) will have a PR to exclude the test, the fix can be done in master or 4.0.

**Comment by spericas** [comment]
@jim-krueger Could you update the target branch?

**Comment by alwin-joseph** [comment]
IIUC https://github.com/jakartaee/rest/pull/1172 has the same fix targeted to release-4.0 which means this PR can either be converted to exclude the test in release-3.1.x or  create a new PR for excluding and abandon this PR . 
Am I right ?

**Comment by jim-krueger** [comment]
Please pardon my confusion.   But if a 3.1.4 version is being created, why not just include this fix rather than excluding the test?

**Comment by spericas** [comment]
On Aug 30, 2023, at 2:08 PM, Jim Krueger ***@***.***> wrote:


Please pardon my confusion. But if a 3.1.4 version is being created, why not just include this fix rather than excluding the test?


 Modifying a test in the same 3.1.X release may cause another implementation that is already passing the TCKs to fail. In general TCKs are disabled and fixed in a future version (dot rather than dot-dot). But Alwin is really the expert here.

— Santiago

**Comment by jim-krueger** [comment]
I see.   That makes sense but it doesn’t apply in this case.   The problem that is fixed with this PR is to remove the previous order requirement for returned messages that was there before.   Removing that order check could not possibly affect any implementation where the test currently works, but would keep this issue from occurring intermittently.    But if Alwin or others feel strongly about this I will exclude the test in 3.1.4.    Thanks

**Comment by spericas** [comment]
On Aug 31, 2023, at 10:42 AM, Jim Krueger ***@***.***> wrote:


I see. That makes sense but it doesn’t apply in this case. The problem that is fixed with this PR is to remove the previous order requirement for returned messages that was there before. Removing that order check could not possibly affect any implementation where the test currently works, but would keep this issue from occurring intermittently. But if Alwin or others feel strongly about this I will exclude the test in 3.1.4. Thanks

 It’s a general rule, not specific to this case. In fact, it is possible for a “fix” to introduce a new problem that wasn’t seen before (regardless of how good the fix is), so it is just safer to omit the test until the next round.

— Santiago

**Comment by alwin-joseph** [comment]
> I see. That makes sense but it doesn’t apply in this case. The problem that is fixed with this PR is to remove the previous order requirement for returned messages that was there before. Removing that order check could not possibly affect any implementation where the test currently works, but would keep this issue from occurring intermittently. But if Alwin or others feel strongly about this I will exclude the test in 3.1.4. Thanks
>

Yes it is possible to fix tests in a service release as I mentioned in https://github.com/jakartaee/rest/pull/1164#issuecomment-1652867664 , referring to https://jakarta.ee/committees/specification/tckprocess/ (especially under section "Accepted Challenges"). 

From the process document : 

"_if there is already at least one certified compatible implementation before the challenge, the new, modified TCK should be run against at least one such implementation (and ideally all of them) before the changes are published, released, and finalized._

_If such a change were released, and it was later found to cause a previously-certified implementation to fail the new, modified test, then excluding the test would likely be the only option, and this would require yet another, additional service release._"

Not against the fix, but only looked safer and easier option to exclude the test. If the REST spec team feel that this test is vital to be not excluded in 3.1.4 we could try fixing it. Thoughts ?

> It’s a general rule, not specific to this case. In fact, it is possible for a “fix” to introduce a new problem that wasn’t seen before (regardless of how good the fix is), so it is just safer to omit the test until the next round.

Agree.

**Comment by jim-krueger** [comment]
As requested, I have excluded/disabled the test  for 3.1.4.

**Review by alwin-joseph — APPROVED** [review]
LGTM

**Comment by jim-krueger** [comment]
I need a couple more approvals before I can merge this.

**Review by alwin-joseph — COMMENTED** [review]
I just noticed that the `org.junit.jupiter.api.Disabled` is not imported in the class. Can you please add the same.

**Comment by jim-krueger** [comment]
@alwin-joseph Thanks for catching this obvious mistake!  Added fast-track as well.

**Comment by jim-krueger** [comment]
@alwin-joseph @jansupol @jamezp Could I possibly talk one of you three into reviewing/approving this so I'd have the required 3 approvals to merge?   Thanks

**Review by jansupol — APPROVED** [review]

**Pull request merged**
