### PR TITLE
[#859]:Allow SseEventSink.close() to throw IOException

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Comment by jimma** [comment]
@andymc12 Done. Thanks Andy.

**Review by chkal — DISMISSED** [review]

**Review by andymc12 — DISMISSED** [review]
Looks good, thanks again for the changes!

**Comment by jansupol** [comment]
Please [see ](https://github.com/eclipse-ee4j/jaxrs-api/issues/859#issuecomment-633725196) my comment.

**Comment by ronsigal** [comment]
We had a longish discussion related to this proposal. On one side, someone suggested that calling close() should put an end to any further activity. My concern, on the other side, was that a failure to flush the stream upon closing was at least worth noting, whatever you choose to do about it. So I vote +1.

But I think that @jansupol is right that this is a breaking change. So, +1 for merging to 4..0.

**Comment by chkal** [comment]
I agree that the change should be done in a major version. Unfortunately we don't have a branch for 4.0 yet. And I don't think that we should create one now. So maybe we should park this one for a while?

**Comment by mkarg** [comment]
I added this PR to the milestone, so at least we don't forget it. :-)

**Comment by spericas** [comment]
@jimma Please re-target this PR to branch 4.0-SNAPSHOT

**Comment by mkarg** [comment]
@jimma Can you please fix the conflicts please? Thanks!

**Comment by jimma** [comment]
@mkarg  Done. Thanks.

**Review by asoldano — DISMISSED** [review]

**Review by chkal — DISMISSED** [review]
I prefer `IOException` over `UncheckedIOException` TBH. I guess in most cases, users will catch and ignore (and maybe log) it. And with `UncheckedIOException` it is too easy to miss catching it.

**Review by spericas — COMMENTED** [review]
This PR should include updates to the TCKs now (in our workspace). They won't compile with the addition of the new exception. Elsewhere our CI pipeline needs to be updated as well.

**Comment by jimma** [comment]
> This PR should include updates to the TCKs now (in our workspace). They won't compile with the addition of the new exception. Elsewhere our CI pipeline needs to be updated as well.

Fixed the tck. Thanks for the review @spericas

**Review by asoldano — APPROVED** [review]
The TCK changes are here: https://github.com/jakartaee/rest/pull/863/commits/23f86b34483050b2cdfbdfbeefd8b9d76056221f can these be merged now?

**Review by spericas — APPROVED** [review]

**Comment by spericas** [comment]
> The TCK changes are here: [23f86b3](https://github.com/jakartaee/rest/commit/23f86b34483050b2cdfbdfbeefd8b9d76056221f) can these be merged now?

Thanks for the TCK changes

**Pull request merged**
