### PR TITLE
Add changes from release-3.1.x and release-4.0 TCK to release-3.2

### PR DESCRIPTION
**Pull request by jim-krueger**
Pulled in changes from the following 3.1.x PR's:

https://github.com/jakartaee/rest/pull/1139
https://github.com/jakartaee/rest/pull/1173
https://github.com/jakartaee/rest/pull/1181
https://github.com/jakartaee/rest/pull/1184
https://github.com/jakartaee/rest/pull/1200

Pulled in changes from the following 4.0 PR's:

https://github.com/jakartaee/rest/pull/863
https://github.com/jakartaee/rest/pull/1146
https://github.com/jakartaee/rest/pull/1164
https://github.com/jakartaee/rest/pull/1172
https://github.com/jakartaee/rest/pull/1182

Removed changes from [PR 864](https://github.com/jakartaee/rest/pull/863) since this change is a breaking change and needs to go in a full release.

Still needs fix to [Issue 1138](https://github.com/jakartaee/rest/issues/1138) and then the exclude list can be updated.

### CODE REVIEW

**Review by jamezp — APPROVED** [review]
This looks good to me. I agree with reverting #863 as well. There was a comment on https://github.com/jakartaee/rest/issues/859#issuecomment-633725196 which indicated:
> Anyway, it is a backward-incompatible change, and as such, it should go into a major version, not minor 3.1, imho.

I agree with that statement.

**Review by jansupol — APPROVED** [review]
If time permits, we should come up with a fix for the disabled tests for 3.2

**Comment by alwin-joseph** [comment]
FYI https://github.com/jakartaee/rest/pull/1218 was merged to _release-3.1.x_ yesterday, might want to update the exclude list file jaxrs-tck-docs/TCK-Exclude-List.txt with that. 

Another option to consider would be to include the fix https://github.com/jakartaee/rest/pull/1201 for those challenged tests from master and enable the tests excluded in https://github.com/jakartaee/rest/pull/1200.

**Review by asoldano — APPROVED** [review]

**Review by jamezp — APPROVED** [review]

**Review by jamezp — APPROVED** [review]

**Comment by jim-krueger** [comment]
Updated to include nearly all of the TCK changes in 4.0 as well.   Exceptions to this are noted in the description above.

**Review by jamezp — APPROVED** [review]

**Comment by spericas** [comment]
Could you please review this PR @alwin-joseph?

**Review by spericas — APPROVED** [review]
LGTM, but we should get @alwin-joseph to review as well.

**Review by alwin-joseph — APPROVED** [review]
+1

**Review by asoldano — APPROVED** [review]

**Pull request merged**
